"""Initial schema

Revision ID: 5206bd3d077d
Revises: 
Create Date: 2026-08-31 20:09:12.769750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5206bd3d077d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('priority_tier', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=False)
    op.create_table('materials',
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('criticality', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_index(op.f('ix_materials_material_id'), 'materials', ['material_id'], unique=False)
    op.create_table('plants',
    sa.Column('plant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DISRUPTED', name='entitystatus'), nullable=True),
    sa.Column('daily_capacity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('plant_id')
    )
    op.create_index(op.f('ix_plants_plant_id'), 'plants', ['plant_id'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('priority_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.create_table('routes',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('transport_mode', sa.String(), nullable=False),
    sa.Column('transit_time_days', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DISRUPTED', name='entitystatus'), nullable=True),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_index(op.f('ix_routes_route_id'), 'routes', ['route_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DISRUPTED', name='entitystatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    op.create_index(op.f('ix_scenarios_scenario_id'), 'scenarios', ['scenario_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DISRUPTED', name='entitystatus'), nullable=True),
    sa.Column('capacity', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_index(op.f('ix_suppliers_supplier_id'), 'suppliers', ['supplier_id'], unique=False)
    op.create_table('customer_orders',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_TRANSIT', 'DELIVERED', 'DELAYED', 'AT_RISK', name='orderstatus'), nullable=True),
    sa.Column('revenue_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_customer_orders_order_id'), 'customer_orders', ['order_id'], unique=False)
    op.create_table('disruptions',
    sa.Column('disruption_id', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('SUPPLIER_FAILURE', 'ROUTE_DELAY', 'PLANT_SHUTDOWN', 'MATERIAL_SHORTAGE', 'DEMAND_SPIKE', name='disruptiontype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='disruptionseverity'), nullable=False),
    sa.Column('target_entity_id', sa.String(), nullable=False),
    sa.Column('target_entity_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('estimated_duration_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DISRUPTED', name='entitystatus'), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.scenario_id'], ),
    sa.PrimaryKeyConstraint('disruption_id')
    )
    op.create_index(op.f('ix_disruptions_disruption_id'), 'disruptions', ['disruption_id'], unique=False)
    op.create_table('inventories',
    sa.Column('inventory_id', sa.String(), nullable=False),
    sa.Column('plant_id', sa.String(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('available_quantity', sa.Float(), nullable=False),
    sa.Column('safety_stock', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.plant_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    op.create_index(op.f('ix_inventories_inventory_id'), 'inventories', ['inventory_id'], unique=False)
    op.create_table('plant_materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.String(), nullable=True),
    sa.Column('material_id', sa.String(), nullable=True),
    sa.Column('required_quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.plant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_plans',
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('action_type', sa.Enum('ALTERNATIVE_SUPPLIER', 'INVENTORY_REALLOCATION', 'REROUTE', name='actiontype'), nullable=False),
    sa.Column('action_details', sa.String(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('mitigated_risk_value', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RECOMMENDED', 'APPROVED', 'REJECTED', name='planstatus'), nullable=True),
    sa.Column('ai_reasoning', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.scenario_id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_recovery_plans_plan_id'), 'recovery_plans', ['plan_id'], unique=False)
    op.create_table('supplier_materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.String(), nullable=True),
    sa.Column('material_id', sa.String(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_materials')
    op.drop_index(op.f('ix_recovery_plans_plan_id'), table_name='recovery_plans')
    op.drop_table('recovery_plans')
    op.drop_table('plant_materials')
    op.drop_index(op.f('ix_inventories_inventory_id'), table_name='inventories')
    op.drop_table('inventories')
    op.drop_index(op.f('ix_disruptions_disruption_id'), table_name='disruptions')
    op.drop_table('disruptions')
    op.drop_index(op.f('ix_customer_orders_order_id'), table_name='customer_orders')
    op.drop_table('customer_orders')
    op.drop_index(op.f('ix_suppliers_supplier_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_scenarios_scenario_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_routes_route_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_plants_plant_id'), table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_materials_material_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
